[tool.poetry]
name = "PyPortfolioOpt"
version = "1.4.1"
description = "Financial portfolio optimization in python"
license = "MIT"
authors = ["Robert Andrew Martin <martin.robertandrew@gmail.com>"]
readme = "README.md"
repository = "https://github.com/robertmartin8/PyPortfolioOpt"
documentation = "https://pyportfolioopt.readthedocs.io/en/latest/"
keywords= ["finance", "portfolio", "optimization", "quant", "investing"]
classifiers=[
        "Development Status :: 4 - Beta",
        "Environment :: Console",
        "Intended Audience :: Financial and Insurance Industry",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: MIT License",
        "Natural Language :: English",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3 :: Only",
        "Topic :: Office/Business :: Financial",
        "Topic :: Office/Business :: Financial :: Investment",
        "Topic :: Scientific/Engineering :: Mathematics",
    ]
packages = [ {include = "pypfopt"} ]

[tool.poetry.urls]
"Issues" = "https://github.com/robertmartin8/PyPortfolioOpt/issues"
"Personal website" = "https://reasonabledeviations.com"

[tool.poetry.dependencies]
python = "^3.6.1"
numpy = "^1.12"
scipy = "^1.3"
pandas = ">=0.19"
cvxpy = "^1.1.10"
cvxopt = {version="^1.2, !=1.2.5.post1", optional=true }
scikit-learn = {version = "^0.24.1", optional=true }
matplotlib = { version = "^3.2.0", optional=true }

[tool.poetry.dev-dependencies]
pytest = "^4.6"
flake8 = "^3.7"
jupyter = "^1.0.0"
black = "^20.8b1"
ipykernel = "^5.4.3"
jedi = "0.17.2"
pytest-cov = "^2.11.1"
yfinance = "^0.1.55"

[tool.poetry.extras]
optionals = ["scikit-learn", "matplotlib", "cvxopt"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

